package com.swp391.condocare_swp.service;

import com.swp391.condocare_swp.dto.StaffCreateRequest;
import com.swp391.condocare_swp.dto.StaffUpdateRequest;
import com.swp391.condocare_swp.entity.Role;
import com.swp391.condocare_swp.entity.Staff;
import com.swp391.condocare_swp.repository.RoleRepository;
import com.swp391.condocare_swp.repository.StaffRepository;
import com.swp391.condocare_swp.security.SecurityUtils;
import com.swp391.condocare_swp.util.PasswordUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.jpa.domain.Specification;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import jakarta.persistence.criteria.Predicate;
import java.time.LocalDateTime;
import java.util.*;
import java.util.concurrent.atomic.AtomicInteger;

/**
 * StaffManagementService — Quản lý nhân viên.
 *
 * THAY ĐỔI:
 *   - Bỏ import SecureRandom, SecurityContextHolder, Authentication (không còn dùng trực tiếp)
 *   - Bỏ private generateRandomPassword() → dùng PasswordUtils.generateRandomPassword()
 *   - deleteStaff(): bỏ SecurityContextHolder inline → dùng SecurityUtils
 */
@Service
public class StaffManagementService {

    private static final Logger logger = LoggerFactory.getLogger(StaffManagementService.class);
    private static final AtomicInteger idCounter = new AtomicInteger(0);

    @Autowired private StaffRepository staffRepo;
    @Autowired private RoleRepository  roleRepo;
    @Autowired private PasswordEncoder passwordEncoder;
    @Autowired private EmailService    emailService;
    @Autowired private SecurityUtils   securityUtils;  // [NEW]

    public Page<Map<String, Object>> listStaff(
            String search, String roleId, String status, PageRequest pageable) {

        Specification<Staff> spec = (root, query, cb) -> {
            List<Predicate> predicates = new ArrayList<>();
            if (search != null && !search.isBlank()) {
                String p = "%" + search.toLowerCase() + "%";
                predicates.add(cb.or(
                        cb.like(cb.lower(root.get("username")),   p),
                        cb.like(cb.lower(root.get("fullName")),   p),
                        cb.like(cb.lower(root.get("email")),      p),
                        cb.like(cb.lower(root.get("phone")),      p),
                        cb.like(cb.lower(root.get("position")),   p),
                        cb.like(cb.lower(root.get("department")), p)
                ));
            }
            if (roleId != null && !roleId.isBlank())
                predicates.add(cb.equal(root.get("role").get("id"), roleId));
            if (status != null && !status.isBlank())
                predicates.add(cb.equal(root.get("status"), Staff.StaffStatus.valueOf(status)));
            return cb.and(predicates.toArray(new Predicate[0]));
        };

        return staffRepo.findAll(spec, pageable).map(this::mapToResponse);
    }

    public Map<String, Object> getStaffDetail(String id) {
        return mapToResponse(staffRepo.findById(id)
                .orElseThrow(() -> new RuntimeException("Không tìm thấy nhân viên: " + id)));
    }

    public List<Map<String, Object>> getAllRoles() {
        return roleRepo.findAll().stream().map(r -> {
            Map<String, Object> m = new LinkedHashMap<>();
            m.put("id", r.getId()); m.put("name", r.getName()); m.put("description", r.getDescription());
            return m;
        }).toList();
    }

    public Map<String, Object> getStats() {
        Map<String, Object> m = new LinkedHashMap<>();
        m.put("total",    staffRepo.count());
        m.put("active",   staffRepo.countByStatus(Staff.StaffStatus.ACTIVE));
        m.put("resigned", staffRepo.countByStatus(Staff.StaffStatus.RESIGNED));
        m.put("onLeave",  staffRepo.countByStatus(Staff.StaffStatus.ON_LEAVE));
        return m;
    }

    @Transactional
    public String createStaff(StaffCreateRequest req) {
        if (staffRepo.existsByUsername(req.getUsername()))
            throw new RuntimeException("Username '" + req.getUsername() + "' đã tồn tại");
        if (req.getEmail() != null && !req.getEmail().isBlank()
                && staffRepo.existsByEmail(req.getEmail()))
            throw new RuntimeException("Email đã được sử dụng bởi nhân viên khác");

        Role role = roleRepo.findById(req.getRoleId())
                .orElseThrow(() -> new RuntimeException("Role không tồn tại: " + req.getRoleId()));

        boolean autoGenerated = (req.getPassword() == null || req.getPassword().isBlank());
        // [THAY ĐỔI] PasswordUtils thay vì private method
        String plainPassword = autoGenerated ? PasswordUtils.generateRandomPassword() : req.getPassword();

        Staff staff = new Staff();
        staff.setId(generateStaffId());
        staff.setUsername(req.getUsername().trim());
        staff.setPassword(passwordEncoder.encode(plainPassword));
        staff.setFullName(req.getFullName().trim());
        staff.setEmail(req.getEmail());
        staff.setPhone(req.getPhone());
        staff.setPosition(req.getPosition() != null ? req.getPosition() : "");
        staff.setDepartment(req.getDepartment() != null ? req.getDepartment() : "");
        staff.setDob(req.getDob());
        staff.setGender(Staff.Gender.valueOf(req.getGender()));
        staff.setRole(role);
        staff.setStatus(Staff.StaffStatus.ACTIVE);
        staff.setHiredAt(req.getHiredAt() != null ? req.getHiredAt() : LocalDateTime.now());

        staffRepo.save(staff);
        logger.info("Created staff: {} ({}) — password {}",
                staff.getId(), staff.getUsername(), autoGenerated ? "auto-generated" : "provided");

        if (autoGenerated && req.getEmail() != null && !req.getEmail().isBlank()) {
            emailService.sendWelcomeEmail(req.getEmail(), staff.getFullName(),
                    staff.getUsername(), plainPassword, "nhân viên");
        }

        return "Tạo nhân viên thành công!" + (autoGenerated ? " Mật khẩu đã được gửi tới email." : "");
    }

    @Transactional
    public String updateStaff(String id, StaffUpdateRequest req) {
        Staff staff = staffRepo.findById(id)
                .orElseThrow(() -> new RuntimeException("Không tìm thấy nhân viên: " + id));

        if (req.getEmail() != null && !req.getEmail().equals(staff.getEmail())
                && staffRepo.existsByEmail(req.getEmail()))
            throw new RuntimeException("Email đã được sử dụng bởi nhân viên khác");

        if (req.getFullName()   != null) staff.setFullName(req.getFullName());
        if (req.getEmail()      != null) staff.setEmail(req.getEmail());
        if (req.getPhone()      != null) staff.setPhone(req.getPhone());
        if (req.getPosition()   != null) staff.setPosition(req.getPosition());
        if (req.getDepartment() != null) staff.setDepartment(req.getDepartment());
        if (req.getDob()        != null) staff.setDob(req.getDob());
        if (req.getGender()     != null) staff.setGender(Staff.Gender.valueOf(req.getGender()));
        if (req.getStatus()     != null) staff.setStatus(Staff.StaffStatus.valueOf(req.getStatus()));
        if (req.getRoleId() != null) {
            staff.setRole(roleRepo.findById(req.getRoleId())
                    .orElseThrow(() -> new RuntimeException("Role không tồn tại")));
        }
        if (req.getNewPassword() != null && !req.getNewPassword().isBlank())
            staff.setPassword(passwordEncoder.encode(req.getNewPassword()));

        staffRepo.save(staff);
        logger.info("Updated staff: {}", id);
        return "Cập nhật thành công!";
    }

    @Transactional
    public String deleteStaff(String id) {
        Staff staff = staffRepo.findById(id)
                .orElseThrow(() -> new RuntimeException("Không tìm thấy nhân viên: " + id));

        // [THAY ĐỔI] securityUtils thay vì SecurityContextHolder inline
        String currentUsername = securityUtils.getCurrentUsername();

        if (staff.getUsername().equals(currentUsername))
            throw new RuntimeException("Bạn không thể tự vô hiệu hóa tài khoản của mình!");

        if ("ADMIN".equalsIgnoreCase(staff.getRole().getName())) {
            Staff currentStaff = securityUtils.getCurrentStaff();
            if (!"ADMIN".equalsIgnoreCase(currentStaff.getRole().getName()))
                throw new RuntimeException("Chỉ ADMIN mới có thể vô hiệu hóa tài khoản ADMIN khác!");
        }

        staff.setStatus(Staff.StaffStatus.RESIGNED);
        staffRepo.save(staff);
        logger.info("Soft-deleted staff: {} by {}", id, currentUsername);
        return "Đã vô hiệu hóa nhân viên thành công!";
    }

    @Transactional
    public String resetPassword(String id) {
        Staff staff = staffRepo.findById(id)
                .orElseThrow(() -> new RuntimeException("Không tìm thấy nhân viên: " + id));

        if (staff.getEmail() == null || staff.getEmail().isBlank())
            throw new RuntimeException(
                    "Nhân viên " + staff.getFullName() + " chưa có địa chỉ email. Vui lòng cập nhật email trước.");

        // [THAY ĐỔI] PasswordUtils
        String newPassword = PasswordUtils.generateRandomPassword();
        staff.setPassword(passwordEncoder.encode(newPassword));
        staffRepo.save(staff);
        logger.info("Password reset for staff [{}] by admin", id);

        emailService.sendWelcomeEmail(staff.getEmail(), staff.getFullName(),
                staff.getUsername(), newPassword, "nhân viên (mật khẩu mới)");

        return "Đã đặt lại mật khẩu và gửi về email: " + staff.getEmail();
    }

    private Map<String, Object> mapToResponse(Staff staff) {
        Map<String, Object> m = new LinkedHashMap<>();
        m.put("id",         staff.getId());
        m.put("username",   staff.getUsername());
        m.put("fullName",   staff.getFullName());
        m.put("email",      staff.getEmail());
        m.put("phone",      staff.getPhone());
        m.put("position",   staff.getPosition());
        m.put("department", staff.getDepartment());
        m.put("dob",        staff.getDob());
        m.put("gender",     staff.getGender().name());
        m.put("roleId",     staff.getRole().getId());
        m.put("roleName",   staff.getRole().getName());
        m.put("status",     staff.getStatus().name());
        m.put("hiredAt",    staff.getHiredAt());
        m.put("lastLogin",  staff.getLastLogin());
        m.put("createAt",   staff.getCreatedAt());
        return m;
    }

    private synchronized String generateStaffId() {
        for (int i = 1; i <= 999; i++) {
            String c = "S" + String.format("%03d", i);
            if (!staffRepo.existsById(c)) return c;
        }
        return "S" + (System.currentTimeMillis() % 100000L) + idCounter.incrementAndGet();
    }
}